- name: Install cron-job
  hosts: ec2
  become_user: ubuntu
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: files/dw-us-east-1.pem
    project_path: /home/ubuntu/auto-package-update
  tasks:
    - name: Copy auto updater to instance
      ansible.posix.synchronize:
        src: ../src/
        dest: "{{project_path}}"

    - name: Install packages
      shell: pip install -r {{project_path}}/requirements.txt

    - name: Register cron job
      ansible.builtin.cron:
        name: "Python Auto Update Job"
        # special_time: hourly
        job: $(cd {{project_path}}; ./main.py)
